//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingChanges
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accent
    {
        public int Id { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string British { get; set; }
        public string American { get; set; }
    }
}
